#!/bin/bash

set -eu

README=README.md

commands=( ubint ubcmd ubread ubwrite )

run_tool() {
	local tool="$1"

	(
		cd src
		python3 -m "ubtools.cli.$tool" "${@:2}"
	)
}

{
	cat <<-EOF
	# ubtools

	### Tiny little tools to interact with U-Boot via the serial console

	Also included is a simple yet robust Python 3.11 library to talk to U-Boot.

	EOF

	echo "| Command | Description |"
	echo "|---|---|"
	for cmd in "${commands[@]}"; do
		echo "| **[$cmd](#$cmd)** | $( run_tool "$cmd" --help 2>&1 | sed -n '/^[^[:space:]]/p' | sed -n '2p' ) |"
	done
	echo

	for cmd in "${commands[@]}"; do
		cat <<-EOF
		### $cmd

		$( run_tool "$cmd" --help 2>&1 | sed -n '/^[^[:space:]]/p' | sed -n '2p' )

		\`\`\`
		$( run_tool "$cmd" --help 2>&1 )
		\`\`\`

		EOF
	done
} >$README 
